# Generated by Django 4.2.2 on 2023-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=500, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("upfit_id", models.IntegerField()),
                ("level", models.CharField(max_length=200)),
                ("sync", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
